Dynamics/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dynamics.Areas.Identity.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Dynamics/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Dynamics.DataAccess.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Newtonsoft.Json;
using System.Text;
using Dynamics.Utility;
using Dynamics.Models.Models;


namespace Dynamics.Areas.Identity.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly IUserRepository _userRepo;
        private readonly SignInManager<User> _signInManager;

        public ConfirmEmailModel(UserManager<User> userManager, IUserRepository userRepo, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _userRepo = userRepo;
            _signInManager = signInManager;
        }

        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string code, string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }
            // Decode and get the result
            var decodedCode = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, decodedCode);
            if (result.Succeeded)
            {
                TempData[MyConstants.Success] = "Your email has been confirmed.";
                TempData[MyConstants.Subtitle] = "Please login again.";
                return Redirect(Url.Page("./Login"));
                // // Sign in
                // await _signInManager.SignInAsync(user, isPersistent: false);
                // // Session
                // var businessUser = await _userRepo.GetAsync(u => u.UserID.ToString() == user.Id);
                // HttpContext.Session.SetString("user", JsonConvert.SerializeObject(businessUser));
                // HttpContext.Session.SetString("currentUserID", businessUser.UserID.ToString());
                // if (User.IsInRole(RoleConstants.Admin) && result.Succeeded)
                // {
                //     return RedirectToAction("Index", "Home", new { area = "Admin" });
                // }
                // return Redirect(returnUrl);
            }
            else
            {
                return RedirectToPage("/Error");
            }
        }

    }
}

Dynamics/Controllers/AuthController.cs
using System.Text;
using System.Text.Encodings.Web;
using Dynamics.Areas.Identity.Pages.Account;
using Dynamics.DataAccess.Repository;
using Dynamics.Models.Dto;
using Dynamics.Models.Models;
using Dynamics.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Shared;

namespace Dynamics.Controllers
{
    public class AuthController : Controller
    {
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly IUserRepository _userRepository;
        private readonly IEmailSender _emailSender;
        private readonly IDataProtectionProvider _dataProtectionProvider;

        public AuthController(SignInManager<User> signInManager, UserManager<User> userManager,
            IUserRepository userRepo, IEmailSender emailSender)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _userRepository = userRepo;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> ResendConfirmationEmail(string email, string? returnUrl = "~/")
        {
            if (string.IsNullOrEmpty(email))
            {
                TempData[MyConstants.Error] = "Please enter your email address inorder to continue";
                return Redirect("/Identity/Account/Login");
            }

            try
            {
                var user = await _userManager.FindByEmailAsync(email);
                var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ConfirmEmail",
                    pageHandler: null,
                    values: new { area = "Identity", userId = user.Id, code = code, returnUrl = returnUrl },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(email, "Confirm your email",
                    $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");
                TempData[MyConstants.Success] = "Confirmation email sent!, please check your mail box";
            }
            catch (Exception e)
            {
                TempData[MyConstants.Error] = "Confirmation email could not be sent.";
                TempData[MyConstants.Subtitle] = e.Message;
                throw;
            }

            return Redirect("/Identity/Account/Login");
        }

        // public async Task<IActionResult> UnbindFromGoogle()
        // {
        //     var user = HttpContext.Session.GetCurrentUser();
        //     var identiyUser = await _userManager.FindByIdAsync(user.UserID.ToString());
        //     var logins = await _userManager.GetLoginsAsync(identiyUser);
        //     
        //     _userManager.RemoveLoginAsync()
        // }

        public async Task<IActionResult> AddPasswordToAccount(ChangePasswordDto changePasswordDto)
        {
            var user = HttpContext.Session.GetCurrentUser();
            var identiyUser = await _userManager.FindByIdAsync(user.Id.ToString());
            if (identiyUser == null) throw new Exception("No user found");
            var result = _userManager.AddPasswordAsync(identiyUser, changePasswordDto.NewPassword);
            if (result.Result.Succeeded)
            {
                TempData[MyConstants.Success] = "Password added to account successfully";
            }
            else
            {
                TempData[MyConstants.Error] = "Password could not be added to the account";
            }
            return RedirectToAction("Edit", "User");
        }
        

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            HttpContext.Session.Clear(); // Clear the session
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Dynamics/Controllers/OrganizationController.cs
using Dynamics.DataAccess.Repository;
using Dynamics.Models.Dto;
using Dynamics.Models.Models;
using Dynamics.Models.Models.ViewModel;
using Dynamics.Services;
using Dynamics.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Evaluation;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using System.Web.Helpers;
using AutoMapper;

namespace Dynamics.Controllers
{
    public class OrganizationController : Controller
    {
        private readonly IOrganizationRepository _organizationRepository;
        private readonly IUserRepository _userRepository;
        private readonly IProjectRepository _projectRepository;
        private readonly IOrganizationVMService _organizationService;
        private readonly IUserToOragnizationTransactionHistoryVMService _userToOragnizationTransactionHistoryVMService;
        private readonly IProjectVMService _projectVMService;
        private readonly IOrganizationToProjectHistoryVMService _organizationToProjectHistoryVMService;
        private readonly CloudinaryUploader _cloudinaryUploader;
        private readonly IOrganizationService _orgDisplayService;
        private readonly IOrganizationMemberRepository _organizationMemberRepository;
        private readonly IOrganizationResourceRepository _organizationResourceRepository;
        private readonly INotificationService _notificationService;

        private readonly IUserToOrganizationTransactionHistoryRepository
            _userToOrganziationTransactionHistoryRepository;

        private readonly IOrganizationToProjectTransactionHistoryRepository
            _organizationToProjectTransactionHistoryRepository;

        private readonly ITransactionViewService _transactionViewService;
        private readonly IPagination _pagination;
        private readonly IRoleService _roleService;
        private readonly IProjectMemberRepository _projectMemberRepository;
        private readonly IMapper _mapper;
        private readonly IProjectResourceRepository _projectResourceRepository;
        private readonly IProjectService _projectService;
        private readonly IWalletService _walletService;

        public OrganizationController(IOrganizationRepository organizationRepository,
            IUserRepository userRepository,
            IProjectRepository projectRepository,
            IOrganizationVMService organizationService,
            IUserToOragnizationTransactionHistoryVMService userToOragnizationTransactionHistoryVMService,
            IProjectVMService projectVMService,
            IOrganizationToProjectHistoryVMService organizationToProjectHistoryVMService,
            CloudinaryUploader cloudinaryUploader, IOrganizationService orgDisplayService,
            IOrganizationMemberRepository organizationMemberRepository,
            IOrganizationResourceRepository organizationResourceRepository, INotificationService notificationService,
            IUserToOrganizationTransactionHistoryRepository userToOrganizationTransactionHistoryRepository,
            IOrganizationToProjectTransactionHistoryRepository organizationToProjectTransactionHistoryRepository,
            IProjectService projectService,
            IMapper mapper, IProjectResourceRepository projectResourceRepository,
            ITransactionViewService transactionViewService, IPagination pagination, IRoleService roleService,
            IProjectMemberRepository projectMemberRepository, IWalletService walletService)
        {
            _organizationRepository = organizationRepository;
            _userRepository = userRepository;
            _projectRepository = projectRepository;
            _organizationService = organizationService;
            _userToOragnizationTransactionHistoryVMService = userToOragnizationTransactionHistoryVMService;
            _projectVMService = projectVMService;
            _organizationToProjectHistoryVMService = organizationToProjectHistoryVMService;
            _cloudinaryUploader = cloudinaryUploader;
            _orgDisplayService = orgDisplayService;
            _organizationMemberRepository = organizationMemberRepository;
            _organizationResourceRepository = organizationResourceRepository;
            _notificationService = notificationService;
            _userToOrganziationTransactionHistoryRepository = userToOrganizationTransactionHistoryRepository;
            _organizationToProjectTransactionHistoryRepository = organizationToProjectTransactionHistoryRepository;
            _transactionViewService = transactionViewService;
            _pagination = pagination;
            _roleService = roleService;
            _projectMemberRepository = projectMemberRepository;
            _mapper = mapper;
            _projectResourceRepository = projectResourceRepository;
            _walletService = walletService;
            _projectService = projectService;
        }

        //The index use the cards at homepage to display instead - Kiet
        public async Task<IActionResult> Index()
        {
            var orgs = _organizationRepository.GetAll(org => org.OrganizationStatus == 1);
            var organizationVMs = _orgDisplayService.MapToOrganizationOverviewDtoList(await orgs.ToListAsync());
            return View(organizationVMs);
        }

        //GET: /Organization/Create
        [HttpGet]
        public IActionResult Create()
        {
            //get current user
            var userString = HttpContext.Session.GetString("user");
            User currentUser = null;
            if (userString != null)
            {
                currentUser = JsonConvert.DeserializeObject<User>(userString);
            }

            if (currentUser.UserAddress == null || currentUser.PhoneNumber == null)
            {
                TempData[MyConstants.Error] = "You need update Your profile before Create new organization";
                return RedirectToAction("Edit", "User");
            }

            var organization = new Organization()
            {
                OrganizationID = Guid.NewGuid(),
                StartTime = DateOnly.FromDateTime(DateTime.UtcNow),
                OrganizationEmail = currentUser.Email,
                OrganizationPhoneNumber = currentUser.PhoneNumber,
                OrganizationAddress = currentUser.UserAddress,
            };
            return View(organization);
        }

        //POST: /Organizations/Create
        [HttpPost]
        public async Task<IActionResult> Create(Organization organization, List<IFormFile> images)
        {
            // Check if user already has an organization
            //get current user
            try
            {
                var userString = HttpContext.Session.GetString("user");
                User currentUser = null;
                if (userString != null)
                {
                    currentUser = JsonConvert.DeserializeObject<User>(userString);
                }

                var existOrg = await _organizationRepository.GetOrganizationUserLead(currentUser.Id);
                if (existOrg != null)
                {
                    TempData[MyConstants.Error] = "Create organization failed!";
                    TempData[MyConstants.Subtitle] = "You already a leader of an organization";
                    return View(organization);
                }

                //set picture for Organization
                if (images.Count != 0)
                {
                    // organization.OrganizationPictures = Util.UploadImage(image, @"images\Organization");
                    var resImages = await _cloudinaryUploader.UploadMultiImagesAsync(images);
                    if (!(resImages.Equals("Wrong extension") || resImages.Equals("No file")))
                    {
                        organization.OrganizationPictures = resImages;
                    }
                    else
                    {
                        TempData[MyConstants.Error] = resImages.Equals("No file")
                            ? "No file to upload!"
                            : "Extension of some files is wrong!";
                    }
                }
                else
                {
                    organization.OrganizationPictures = "/images/defaultOrg.jpg";
                }

                if (userString != null)
                {
                    currentUser = JsonConvert.DeserializeObject<User>(userString);
                }

                //set contact for Organization
                if (organization.OrganizationEmail == null)
                {
                    organization.OrganizationEmail = currentUser.Email;
                }

                if (organization.OrganizationPhoneNumber == null)
                {
                    organization.OrganizationPhoneNumber = currentUser.PhoneNumber;
                }

                if (organization.OrganizationAddress == null)
                {
                    organization.OrganizationAddress = currentUser.UserAddress;
                }

                var result = await _organizationRepository.AddOrganizationAsync(organization);
                if (result)
                {
                    var organizationResource = new OrganizationResource()
                    {
                        OrganizationID = organization.OrganizationID,
                        ResourceName = "Money",
                        Quantity = 0,
                        Unit = "VND",
                    };
                    await _organizationRepository.AddOrganizationResourceSync(organizationResource);
                    await _roleService.AddUserToRoleAsync(currentUser.Id, RoleConstants.HeadOfOrganization);
                    TempData[MyConstants.Success] = "Create organization successfully!";
                    return RedirectToAction(nameof(JoinOrganization),
                        new
                        {

Dynamics/Views/User/Account.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Newtonsoft.Json
@inject IHttpContextAccessor Accessor
@model Dynamics.Models.Dto.ChangePasswordDto

@{
    ViewData["Title"] = "Account";
    Layout = "CustomLayout/_LayoutWithNavbarOnly";
}

@{
    var userString = Accessor.HttpContext.Session.GetString("user");
    User currentUser = null;
    if (userString != null)
    {
        currentUser = JsonConvert.DeserializeObject<User>(userString);
    }
}

<!-- Edit profile -->
<main class="flex md:p-6 pb-0 flex-1 h-screen">
    @*     <!-- Sidebar -->
    <div class="p-2 pt-12 w-1/5">
    <ul class="flex flex-col gap-2">
    <a asp-action="Edit" asp-controller="User" asp-route-id="@currentUser.UserID" class="btn btn-ghost text-start"> Change profile </a>
    <a asp-action="Account" class="btn btn-ghost text-start btn-active"> Account </a>
    <a href="settings/history" class="btn btn-ghost text-start"> History </a>
    <a href="settings/awards" class="btn btn-ghost text-start"> Awards </a>
    </ul>
    </div>
    <!-- End sidebar --> *@
    @await Html.PartialAsync("CustomComponent/_UserSidebar", "Account")

    <!-- Main content -->
    <div class="divider divider-horizontal"></div>
    <div class="flex flex-col gap-2 items-center w-full max-w-screen-xl mx-auto">
        @if (TempData["Google"] != null)
        {
            <h2 class="mb-4 text-center text-3xl font-bold text-success">@TempData["Google"]</h2>
            <h3 class="text-xl">Link your account to Dynamics account by adding a password: </h3>
            <form asp-action="AddPasswordToAccount" asp-controller="Auth" method="get"
                  class="flex flex-col gap-4 justify-center items-center w-full max-w-md">
                <div asp-validation-summary="ModelOnly" class="text-error" role="alert"></div>
                @* New password *@
                <label class="form-control w-full">
                    <span class="label label-text font-bold text-lg">New password</span>
                    <input type="password"
                           placeholder="Please enter your new password"
                           class="input input-bordered w-full bg-white input-info"
                           asp-for="@Model.NewPassword"
                           name="NewPassword"
                           required/>
                    <span asp-validation-for="NewPassword" class="text-error"></span>
                </label>

                @* Confirm password *@
                <label class="form-control w-full">
                    <span class="label label-text font-bold text-lg">Confirm new password</span>
                    <input type="password"
                           placeholder="Please enter your confirm new password"
                           class="input input-bordered w-full bg-white input-info"
                           required
                           asp-for="@Model.ConfirmPassword"/>
                    <span asp-validation-for="ConfirmPassword" class="text-error"></span>
                </label>
                <button type="submit" data-mdb-button-init data-mdb-ripple-init
                        class="btn btn-primary"
                        id="login">
                    Add password
                </button>
            </form>
        }
        else
        {
            <form asp-action="ChangePassword" asp-controller="User" method="post"
                  class="flex flex-col gap-4 justify-start items-center w-full p-16">
                <h2 class="mb-4 text-center text-3xl">
                    <b>Change password</b>
                </h2>
                <div asp-validation-summary="ModelOnly" class="text-error" role="alert"></div>
                @if (currentUser.Id != null)
                {
                    <input type="hidden" asp-for="@Model.UserId" value="@currentUser.Id"/>
                }

                @* Old password *@
                <label class="form-control w-full">
                    <span class="label label-text font-bold text-lg">Old password</span>
                    <input type="password"
                           placeholder="Please enter your old password"
                           class="input input-bordered w-full bg-white input-info"
                           asp-for="@Model.OldPassword"
                           name="OldPassword"/>
                    <span asp-validation-for="OldPassword" class="text-error"></span>
                </label>
                @* New password *@
                <label class="form-control w-full">
                    <span class="label label-text font-bold text-lg">New password</span>
                    <input type="password"
                           placeholder="Please enter your new password"
                           class="input input-bordered w-full bg-white input-info"
                           asp-for="@Model.NewPassword"
                           name="NewPassword"/>
                    <span asp-validation-for="NewPassword" class="text-error"></span>
                </label>

                @* Confirm password *@
                <label class="form-control w-full">
                    <span class="label label-text font-bold text-lg">Confirm new password</span>
                    <input type="password"
                           placeholder="Please enter your confirm new password"
                           class="input input-bordered w-full bg-white input-info"
                           asp-for="@Model.ConfirmPassword"/>
                    <span asp-validation-for="ConfirmPassword" class="text-error"></span>
                </label>
                <button type="submit" data-mdb-button-init data-mdb-ripple-init
                        class="btn btn-primary"
                        id="login">
                    Save change
                </button>
            </form>
        }
    </div>
    <!-- End content -->
</main>
<!-- End edit profile -->
<partial name="CustomComponent/_SweetAlertToast"/>

Dynamics/Views/User/Index.cshtml
@using Dynamics.Utility
@model Dynamics.Models.Models.ViewModel.UserVM
@inject IRoleService roleService

@{
ViewData["Title"] = "Details";
}
<div class="container mx-auto my-5 p-5" style="height: calc(100vh - 143px)">
    <div class="md:flex no-wrap md:-mx-2 ">
        <!-- Left Side -->
        <div class=" md:w-3/12 md:mx-2">
            <!-- Profile Card -->
            <div class="bg-white p-3 border-t-4 border-green-400">
                <div class="image overflow-hidden">
                    <img class="h-[300px] object-cover w-full mx-auto"
                         alt="@Model.UserName" src="@Model.UserAvatar">
                </div>
                <h1 class="text-gray-900 font-bold text-xl leading-8 my-1">@Html.DisplayFor(model => model.UserName)</h1>
                <h3 class="text-gray-600 font-lg text-semibold leading-6">
                    @if (Model.OrganizationName != null)
                    {
                        <span>Leader of <a asp-action="Detail" asp-controller="Organization" asp-route-organizationId="@Model.OrganizationId" class="link link-primary">@Model.OrganizationName</a></span>
                    }
                </h3>
                @* <p class="text-sm text-gray-500 hover:text-gray-600 leading-6">@Html.DisplayFor(model => model.UserDescription)</p> *@
                <ul class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
                    <li class="flex items-center py-3">
                        <span>Status</span>
                        <span class="ml-auto">
                            @if (await roleService.IsInRoleAsync(Model.Id, RoleConstants.Banned))
                            {
                                <span class="bg-error py-1 px-2 rounded text-white text-sm">Banned</span>
                            }
                            else
                            {
                                <span class="bg-success py-1 px-2 rounded text-white text-sm">Active</span>
                            }
                        </span>
                    </li>
                    <li class="flex items-center py-3">
                        <span>Member since</span>
                        <span class="ml-auto">@Html.DisplayFor(m => m.CreatedDate)</span>
                    </li>
                </ul>
            </div>
            <!-- End of profile card -->
            <div class="my-4"></div>
            @* <!-- Friends card --> *@
            @* <div class="bg-white p-3 hover:shadow"> *@
            @*     <div class="flex items-center space-x-3 font-semibold text-gray-900 text-xl leading-8"> *@
            @*         <span class="text-green-500"> *@
            @*             <svg class="h-5 fill-current" xmlns="http://www.w3.org/2000/svg" fill="none" *@
            @*                  viewBox="0 0 24 24" stroke="currentColor"> *@
            @*                 <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" *@
            @*                       d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"/> *@
            @*             </svg> *@
            @*         </span> *@
            @*         <span>Similar Profiles</span> *@
            @*     </div> *@
            @*     <div class="grid grid-cols-3"> *@
            @*         <div class="text-center my-2"> *@
            @*             <img class="h-16 w-16 rounded-full mx-auto" *@
            @*                  src="https://cdn.australianageingagenda.com.au/wp-content/uploads/2015/06/28085920/Phil-Beckett-2-e1435107243361.jpg" *@
            @*                  alt=""> *@
            @*             <a href="#" class="text-main-color">Kojstantin</a> *@
            @*         </div> *@
            @*     </div> *@
            @* </div> *@
            @* <!-- End of friends card --> *@
        </div>


        <!-- Right Side -->
        <div class="w-full md:w-9/12 mx-2 h-64">

            <!-- Profile tab -->
            <!-- About Section -->
            <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                    <span clas="text-green-500">
                        <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                             stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
                        </svg>
                    </span>
                    <span class="tracking-wide">About</span>
                </div>

                <div class="text-gray-700">
                    <div class="grid md:grid-cols-2 text-sm">
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Full Name</div>
                            <div class="px-4 py-2">@Html.DisplayFor(model => model.UserName)</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Contact No.</div>
                            <div class="px-4 py-2">@Html.DisplayFor(model => model.PhoneNumber)</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Address</div>
                            <div class="px-4 py-2">@Html.DisplayFor(model => model.UserAddress)</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Email.</div>
                            <div class="px-4 py-2">
                                <a class="text-blue-800"> @Html.DisplayFor(model => model.Email)</a>
                            </div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Birthday</div>
                            <div class="px-4 py-2"> @Html.DisplayFor(model => model.UserDOB)</div>
                        </div>
                    </div>
                </div>
                @* <button class="block w-full text-blue-800 text-sm font-semibold rounded-lg hover:bg-gray-100 focus:outline-none focus:shadow-outline focus:bg-gray-100 hover:shadow-xs p-3 my-4"> *@
                @*     Show *@
                @*     Full Information *@
                @* </button> *@
            </div>
            <!-- End of about section -->

            <div class="my-4"></div>

            <!-- Experience and education -->
            <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="flex gap-4">
                    <svg class="w-6 h-6 text-black" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 9h3m-3 3h3m-3 3h3m-6 1c-.306-.613-.933-1-1.618-1H7.618c-.685 0-1.312.387-1.618 1M4 5h16a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Zm7 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
                    </svg>
                    Introduction
                </div>
                <div class="text-neutral">
                    @Model.UserDescription
                </div>
                <!-- End of Experience and education grid -->
            </div>
            <!-- End of profile tab -->
        </div>
    </div>
</div>